### ISSUE TITLE
ubunutu not support

### ISSUE THREAD

**Issue by ghost** [M-Adoo/easy-skia#1]
ubuuntu 我该怎么使用呢?

**Comment by M-Adoo** [comment]
还是进行中，目前上在OSX上做的，api 包装的差不多以后，会再对其它平台验证，你可以试试

```
cargo run  --example safe
```
有没有画出图片。

**Comment by ghost** [comment]
我这样改的不能运行,报错一堆应该是链接失败 ,我最近尝试使用bindgen从skia的头文件生成rs文件,在配合静态库但是没有成功

// let out_dir = env::var("OUT_DIR").unwrap();

    // let skia_out_dir = format!("{}/skia", &out_dir);

    // assert!(Command::new("python")
    //             .current_dir("skia")
    //             .args(&["tools/git-sync-deps"])
    //             .status().unwrap().success(), "Cannot download skia depenedencies");

    // assert!(Command::new("bin/gn")
    //             .current_dir("skia")
    //             .args(&["gen", &skia_out_dir, "--args=is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"])
    //             .status().unwrap().success(), "Cannot generate build files");

    // assert!(Command::new("ninja")
    //             .current_dir("skia")
    //             .args(&["-C", &skia_out_dir])
    //             .status().unwrap().success(), "Cannot build skia");

    println!("cargo:rustc-link-search=native={}", "/home/orange/work/c/gui/skia/lib/linux/x64/Static");
    println!("cargo:rustc-link-lib=static=skia");
    println!("cargo:rustc-link-lib=stdc++");

    #[cfg(target_os="macos")]
    {
        println!("cargo:rustc-link-lib=framework=CoreFoundation");
        println!("cargo:rustc-link-lib=framework=CoreGraphics");
        println!("cargo:rustc-link-lib=framework=CoreText");
        println!("cargo:rustc-link-lib=framework=CoreServices");
    }
}

**Comment by M-Adoo** [comment]
前面的部分是编译 skia 本身，需要的。osx gpu 的绘制处理完后，我会来看看，ubuntu 的编译。我本身也是需要跨平台的能力来做事。

**Comment by ghost** [comment]
前面的编译我编译过了 ,/home/orange/work/c/gui/skia/lib/linux/x64/Static 这个路经下有编译好的静态库

**Comment by M-Adoo** [comment]
可以贴出错误来看看

**Comment by ghost** [comment]
orange@orange:~/work/rust/material$ cd easy-skia/
orange@orange:~/work/rust/material/easy-skia$ cargo run --example safe
   Compiling easy-skia v0.1.0 (/home/orange/work/rust/material/easy-skia)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.19p6iu8g89g4s5ne.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1a12z0zagbnmd98c.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1b6v0ddnwdubqfaj.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1c8rargvb0fh6f4m.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1eie6swhagv4n3r1.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1jeq3331smt2lp6x.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1pzbg0s7wgja7a2n.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1vkjzk5jck3ntcva.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.2akrwhziptplcs0r.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.2bu8ocsaqoreyrv8.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.2ddm4u2acnh8fbyv.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.33j18v5n6t1332ov.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.3578d38cjrwtdkk2.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.38bsojz7d44cvhm0.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.3e7dlda214yu46bm.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.3l45gc10ldsgv583.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.3nefgutm3lt430dc.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.3vh6yuh89jjpwt3v.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.40o2yojwdzvxjjtl.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.41kh66j5sx30oap4.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.44at1y0fch6yyd6u.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.4eirodkpzkb3h5as.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.4t4gvzz13sul3pof.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.576wa5oqi6l37pbp.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.57vg9hbm5rgst9a1.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.5bn88mlypzuihiia.rcgu.o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.74ezpjkqmmo9civ.rcgu.o" "-o" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28" "/home/orange/work/rust/material/easy-skia/target/debug/examples/safe-c66f69d3c7d7cb28.1pupnz5mfeuscx5m.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/orange/work/rust/material/easy-skia/target/debug/deps" "-L" "/home/orange/work/c/gui/skia/lib/linux/x64/Static" "-L" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib" "-Wl,--start-group" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-dd4752c70d4ce71d.rlib" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e04840eda0100e05.rlib" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-16bfb4d182748e63.rlib" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-185d9b81685a2f08.rlib" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4806247fe4c34e64.rlib" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-879310dc3b96af61.rlib" "-Wl,--end-group" "/home/orange/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d0572f7a936161bf.rlib" "-Wl,-Bdynamic" "-lstdc++" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.11xb638xhq7lekjk.rcgu.o): In function `easy_skia::surface::Surface::new_raster':
          /home/orange/work/rust/material/easy-skia/src/surface.rs:25: undefined reference to `_sk_surface_new_raster'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.11xb638xhq7lekjk.rcgu.o): In function `easy_skia::surface::Surface::get_canvas':
          /home/orange/work/rust/material/easy-skia/src/surface.rs:34: undefined reference to `_sk_surface_get_canvas'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.11xb638xhq7lekjk.rcgu.o): In function `easy_skia::surface::Surface::new_image_snapshot':
          /home/orange/work/rust/material/easy-skia/src/surface.rs:42: undefined reference to `_sk_surface_new_image_snapshot'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.11xb638xhq7lekjk.rcgu.o): In function `<easy_skia::surface::Surface as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/surface.rs:49: undefined reference to `_sk_surface_unref'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.11xb638xhq7lekjk.rcgu.o): In function `easy_skia::surface::SurfaceProps::new':
          /home/orange/work/rust/material/easy-skia/src/surface.rs:60: undefined reference to `_sk_surfaceprops_new'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.11xb638xhq7lekjk.rcgu.o): In function `<easy_skia::surface::SurfaceProps as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/surface.rs:75: undefined reference to `_sk_surfaceprops_delete'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.1r05imyo6cf9q13f.rcgu.o): In function `easy_skia::path::Path::new':
          /home/orange/work/rust/material/easy-skia/src/path.rs:12: undefined reference to `_sk_path_new'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.1r05imyo6cf9q13f.rcgu.o): In function `easy_skia::path::Path::move_to':
          /home/orange/work/rust/material/easy-skia/src/path.rs:21: undefined reference to `_sk_path_move_to'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.1r05imyo6cf9q13f.rcgu.o): In function `easy_skia::path::Path::line_to':
          /home/orange/work/rust/material/easy-skia/src/path.rs:25: undefined reference to `_sk_path_line_to'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.1r05imyo6cf9q13f.rcgu.o): In function `easy_skia::path::Path::cubic_to':
          /home/orange/work/rust/material/easy-skia/src/path.rs:37: undefined reference to `_sk_path_cubic_to'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.1r05imyo6cf9q13f.rcgu.o): In function `<easy_skia::path::Path as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/path.rs:68: undefined reference to `_sk_path_delete'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::new':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:19: undefined reference to `_sk_paint_new'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::set_antialias':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:35: undefined reference to `_sk_paint_set_antialias'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::get_color':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:48: undefined reference to `_sk_paint_get_color'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::set_color':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:53: undefined reference to `_sk_paint_set_color'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::set_stroke_width':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:61: undefined reference to `_sk_paint_set_stroke_width'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::set_text_size':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:89: undefined reference to `_sk_paint_set_textsize'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `easy_skia::paint::Paint::set_typeface':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:97: undefined reference to `_sk_paint_set_typeface'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.2at5lm38kzydhbph.rcgu.o): In function `<easy_skia::paint::Paint as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/paint.rs:195: undefined reference to `_sk_paint_delete'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.38ifb9tiahtzeroz.rcgu.o): In function `easy_skia::canvas::Canvas::draw_paint':
          /home/orange/work/rust/material/easy-skia/src/canvas.rs:51: undefined reference to `_sk_canvas_draw_paint'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.38ifb9tiahtzeroz.rcgu.o): In function `easy_skia::canvas::Canvas::draw_rect':
          /home/orange/work/rust/material/easy-skia/src/canvas.rs:55: undefined reference to `_sk_canvas_draw_rect'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.38ifb9tiahtzeroz.rcgu.o): In function `easy_skia::canvas::Canvas::draw_oval':
          /home/orange/work/rust/material/easy-skia/src/canvas.rs:63: undefined reference to `_sk_canvas_draw_oval'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.38ifb9tiahtzeroz.rcgu.o): In function `easy_skia::canvas::Canvas::draw_path':
          /home/orange/work/rust/material/easy-skia/src/canvas.rs:68: undefined reference to `_sk_canvas_draw_path'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.38ifb9tiahtzeroz.rcgu.o): In function `easy_skia::canvas::Canvas::draw_text':
          /home/orange/work/rust/material/easy-skia/src/canvas.rs:79: undefined reference to `_sk_canvas_draw_text'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.3fpuhnd6zumjm9va.rcgu.o): In function `easy_skia::image::Image::encode':
          /home/orange/work/rust/material/easy-skia/src/image.rs:37: undefined reference to `_sk_image_encode'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.3fpuhnd6zumjm9va.rcgu.o): In function `<easy_skia::image::Image as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/image.rs:56: undefined reference to `_sk_image_unref'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.4leufaym0mjkjzxy.rcgu.o): In function `easy_skia::color_space::ColorSpace::new':
          /home/orange/work/rust/material/easy-skia/src/color_space.rs:10: undefined reference to `_sk_colorspace_new_srgb'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.4leufaym0mjkjzxy.rcgu.o): In function `<easy_skia::color_space::ColorSpace as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/color_space.rs:27: undefined reference to `_sk_colorspace_unref'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.52pytdtmt6hkaltb.rcgu.o): In function `easy_skia::data::Data::size':
          /home/orange/work/rust/material/easy-skia/src/data.rs:42: undefined reference to `_sk_data_get_size'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.52pytdtmt6hkaltb.rcgu.o): In function `easy_skia::data::Data::get_data':
          /home/orange/work/rust/material/easy-skia/src/data.rs:46: undefined reference to `_sk_data_get_data'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.52pytdtmt6hkaltb.rcgu.o): In function `<easy_skia::data::Data as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/data.rs:53: undefined reference to `_sk_data_unref'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.5fjlo52gli671mih.rcgu.o): In function `easy_skia::typeface::Typeface::new_from_file':
          /home/orange/work/rust/material/easy-skia/src/typeface.rs:12: undefined reference to `_sk_typeface_create_from_file'
          /home/orange/work/rust/material/easy-skia/target/debug/deps/libeasy_skia-bf471ad2c7c8bab7.rlib(easy_skia-bf471ad2c7c8bab7.5fjlo52gli671mih.rcgu.o): In function `<easy_skia::typeface::Typeface as core::ops::drop::Drop>::drop':
          /home/orange/work/rust/material/easy-skia/src/typeface.rs:24: undefined reference to `_sk_typeface_unref'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `easy-skia`.

To learn more, run the command again with --verbose.
orange@orange:~/work/rust/material/easy-skia$

**Comment by ghost** [comment]
应该是动态库的链接出了问题

**Comment by ghost** [comment]
像我这种直接生成rust代码更简洁 但是不知道哪个gcc参数咩有设置好链接有点问题
extern crate bindgen;
extern crate cc;


use bindgen::Builder;
use std::env;
use std::path::PathBuf;



fn main() {

    println!("cargo:rustc-link-search=native={}","/home/orange/work/rust/material/main/skia/out/Static");
    let library_test = "skia";
    println!("cargo:rustc-link-lib=static={}", library_test);
    println!("cargo:rustc-link-lib=stdc++");


    let bindings = Builder::default()
        .rustfmt_bindings(false)
        .enable_cxx_namespaces()
        .rustified_enum(".*")
        .raw_line("pub use self::root::*;")  
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/android"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/c"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/codec"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/config"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/core"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/effects"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/encode"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/gpu"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/gpu/gl"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/gpu/mock"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/gpu/mtl"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/gpu/vk"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/pathops"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/ports"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/private"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/utils"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/utils/mac"))
        .clang_arg(format!("-I{}", "/home/orange/work/rust/material/main/skia/include/views"))
        .header("/home/orange/work/rust/material/main/skia/include/core/SkBitmap.h")
        .header("/home/orange/work/rust/material/main/skia/include/core/SkCanvas.h")
        .header("/home/orange/work/rust/material/main/skia/include/core/SkTypeface.h")
        .clang_args(&["-x", "c++", "-std=c++14"])
        .blacklist_type("max_align_t") 
        .ctypes_prefix("libc")
         .use_core()
        .generate()
        .expect("unable to generate rocksdb bindings");

       let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
       bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("unable to write rocksdb bindings");
}

**Comment by M-Adoo** [comment]
d1da45310323f5e2584715c958c539b9d5d6af6b maybe resolve your problem. I had tested on ubuntu 18.04

**Comment by ghost** [comment]
过年也这么拼么？你可以尝试我上面的build.rs的写法，但是报错，因为我对bindgen不太熟悉，不知道哪个参数没有加不

**Comment by ghost** [comment]
你是使skia的c版本接口，我当时c接口测试成功了，我一直以为c接口没有cpp全面，所以放弃了

**Comment by M-Adoo** [comment]
这个 c 接口很全面了。

**Comment by M-Adoo** [comment]
不是官方的c接口。我弄了个vps 试了试没问题，边看东西边改这个，编一次老久了。😂

**Comment by ghost** [comment]
我从来没有编译过，有编译好的动态库直接可以用，我当时用c接口也成功了，但是功能不全就放弃了，你看看我的build.rs是cpp的，但是不知道bindgen怎么改参数，我知道改个参数就好了，

**Comment by ghost** [comment]
你如果用c的话，src下面的代码直接可以去掉，因为bindegn直接生成了rust代码，直接用就可以了，我使用rockdb就这样的，直接把c语言的头文件通过bindgen生成rust代码，然后把生产的rust代码引入到文件直接调用，你src下面的完全可以去掉

**Comment by M-Adoo** [comment]
我不打算用cpp生成的接口来做这个，而是用c接口来包成rust风格的接口，不是直接以C API 的方式来用。你直接 clone 项目build 就可以了，做法并不和你想的完全一致。
